---@meta

-- AUTO-GENERATED FILE. DO NOT EDIT.
-- Generated by tools/gen_lua_metadata.py from C++ Lua bindings.

---@class NS.Audio
Audio = {}
---@type any
Audio.isPlaying = nil
---@type any
Audio.loadMusic = nil
---@type any
Audio.loadSfx = nil
---@type any
Audio.playMusic = nil
---@type any
Audio.playMusicAsync = nil
---@type any
Audio.playSfx = nil
---@type any
Audio.playSfxAsync = nil
---@type any
Audio.release = nil

---@class NS.Entity
Entity = {}
---@type any
Entity.Load = nil

---@class NS.Gameplay
Gameplay = {}
---@type any
Gameplay.Scene = nil
---@type any
Gameplay.cancelTowerPlacement = nil
---@type any
Gameplay.clearDebugSelection = nil
---@type any
Gameplay.getAnimationClips = nil
---@type any
Gameplay.getCompositeAnimationMode = nil
---@type any
Gameplay.getDebugPickSpheresVisible = nil
---@type any
Gameplay.getDebugSelection = nil
---@type any
Gameplay.getLobbyLevels = nil
---@type any
Gameplay.getPickEnabled = nil
---@type any
Gameplay.getSelectedLobbyLevel = nil
---@type any
Gameplay.getState = nil
---@type any
Gameplay.getTowerLoadout = nil
---@type any
Gameplay.getTowerPlacementState = nil
---@type any
Gameplay.playMusic = nil
---@type any
Gameplay.playSfx = nil
---@type any
Gameplay.preloadSfx = nil
---@type any
Gameplay.requestAcceptDisplayChanges = nil
---@type any
Gameplay.requestApplySettings = nil
---@type any
Gameplay.requestDamageBase = nil
---@type any
Gameplay.requestQuit = nil
---@type any
Gameplay.requestRevertDisplayChanges = nil
---@type any
Gameplay.requestScene = nil
---@type any
Gameplay.requestSpendMoney = nil
---@type any
Gameplay.requestStartWave = nil
---@type any
Gameplay.selectLobbyLevel = nil
---@type any
Gameplay.selectTowerSlot = nil
---@type any
Gameplay.setAnimationClip = nil
---@type any
Gameplay.setCompositeAnimationMode = nil
---@type any
Gameplay.setDebugPickSpheresVisible = nil
---@type any
Gameplay.setPickEnabled = nil

---@type any
HeadingFont = nil

---@class NS.ImGui
ImGui = {}
---@type any
ImGui.Begin = nil
---@type any
ImGui.BeginChild = nil
---@type any
ImGui.BeginGroup = nil
---@type any
ImGui.BeginMenu = nil
---@type any
ImGui.BeginMenuBar = nil
---@type any
ImGui.BeginPopup = nil
---@type any
ImGui.BeginPopupModal = nil
---@type any
ImGui.BeginTabBar = nil
---@type any
ImGui.BeginTabItem = nil
---@type any
ImGui.BulletText = nil
---@type any
ImGui.Button = nil
---@type any
ImGui.CalcTextSize = nil
---@type any
ImGui.Checkbox = nil
---@type any
ImGui.CloseCurrentPopup = nil
---@type any
ImGui.CollapsingHeader = nil
---@type any
ImGui.ColorEdit4 = nil
---@type any
ImGui.Combo = nil
---@type any
ImGui.DragFloat = nil
---@type any
ImGui.DragInt = nil
---@type any
ImGui.Dummy = nil
---@type any
ImGui.End = nil
---@type any
ImGui.EndChild = nil
---@type any
ImGui.EndGroup = nil
---@type any
ImGui.EndMenu = nil
---@type any
ImGui.EndMenuBar = nil
---@type any
ImGui.EndPopup = nil
---@type any
ImGui.EndTabBar = nil
---@type any
ImGui.EndTabItem = nil
---@type any
ImGui.GetContentRegionAvail = nil
---@type any
ImGui.GetCursorPos = nil
---@type any
ImGui.GetDisplaySize = nil
---@type any
ImGui.GetFrameHeight = nil
---@type any
ImGui.GetTextLineHeight = nil
---@type any
ImGui.GetWindowHeight = nil
---@type any
ImGui.GetWindowPos = nil
---@type any
ImGui.GetWindowSize = nil
---@type any
ImGui.GetWindowWidth = nil
---@type any
ImGui.Image = nil
---@type any
ImGui.ImageButton = nil
---@type any
ImGui.Indent = nil
---@type any
ImGui.InputFloat = nil
---@type any
ImGui.InputInt = nil
---@type any
ImGui.InputText = nil
---@type any
ImGui.IsItemClicked = nil
---@type any
ImGui.IsItemHovered = nil
---@type any
ImGui.IsKeyPressed = nil
---@type any
ImGui.IsWindowFocused = nil
---@type any
ImGui.IsWindowHovered = nil
---@type any
ImGui.LabelText = nil
---@type any
ImGui.MenuItem = nil
---@type any
ImGui.NewLine = nil
---@type any
ImGui.OpenPopup = nil
---@type any
ImGui.PopFont = nil
---@type any
ImGui.PopStyleColor = nil
---@type any
ImGui.PopStyleVar = nil
---@type any
ImGui.ProgressBar = nil
---@type any
ImGui.PushFont = nil
---@type any
ImGui.PushStyleColor = nil
---@type any
ImGui.PushStyleVar = nil
---@type any
ImGui.RadioButton = nil
---@type any
ImGui.SameLine = nil
---@type any
ImGui.Selectable = nil
---@type any
ImGui.Separator = nil
---@type any
ImGui.SetCursorPos = nil
---@type any
ImGui.SetCursorPosX = nil
---@type any
ImGui.SetCursorPosY = nil
---@type any
ImGui.SetNextWindowBgAlpha = nil
---@type any
ImGui.SetNextWindowFullscreen = nil
---@type any
ImGui.SetNextWindowPos = nil
---@type any
ImGui.SetNextWindowSize = nil
---@type any
ImGui.SetTooltip = nil
---@type any
ImGui.SliderFloat = nil
---@type any
ImGui.SliderInt = nil
---@type any
ImGui.SmallButton = nil
---@type any
ImGui.Spacing = nil
---@type any
ImGui.Text = nil
---@type any
ImGui.TextColored = nil
---@type any
ImGui.TextDisabled = nil
---@type any
ImGui.TextUnformatted = nil
---@type any
ImGui.TextWrapped = nil
---@type any
ImGui.TreeNode = nil
---@type any
ImGui.TreePop = nil
---@type any
ImGui.Unindent = nil

---@class NS.ImGuiCol
ImGuiCol = {}
---@type any
ImGuiCol.Border = nil
---@type any
ImGuiCol.Button = nil
---@type any
ImGuiCol.ButtonActive = nil
---@type any
ImGuiCol.ButtonHovered = nil
---@type any
ImGuiCol.CheckMark = nil
---@type any
ImGuiCol.ChildBg = nil
---@type any
ImGuiCol.FrameBg = nil
---@type any
ImGuiCol.FrameBgActive = nil
---@type any
ImGuiCol.FrameBgHovered = nil
---@type any
ImGuiCol.Header = nil
---@type any
ImGuiCol.HeaderActive = nil
---@type any
ImGuiCol.HeaderHovered = nil
---@type any
ImGuiCol.PopupBg = nil
---@type any
ImGuiCol.Separator = nil
---@type any
ImGuiCol.SliderGrab = nil
---@type any
ImGuiCol.SliderGrabActive = nil
---@type any
ImGuiCol.Text = nil
---@type any
ImGuiCol.TextDisabled = nil
---@type any
ImGuiCol.TitleBg = nil
---@type any
ImGuiCol.TitleBgActive = nil
---@type any
ImGuiCol.WindowBg = nil

---@class NS.ImGuiCond
ImGuiCond = {}
---@type any
ImGuiCond.Always = nil
---@type any
ImGuiCond.Appearing = nil
---@type any
ImGuiCond.FirstUseEver = nil
---@type any
ImGuiCond.None = nil
---@type any
ImGuiCond.Once = nil

---@type any
ImGuiKey = nil

---@class NS.ImGuiStyleVar
ImGuiStyleVar = {}
---@type any
ImGuiStyleVar.Alpha = nil
---@type any
ImGuiStyleVar.FramePadding = nil
---@type any
ImGuiStyleVar.FrameRounding = nil
---@type any
ImGuiStyleVar.GrabMinSize = nil
---@type any
ImGuiStyleVar.GrabRounding = nil
---@type any
ImGuiStyleVar.IndentSpacing = nil
---@type any
ImGuiStyleVar.ItemInnerSpacing = nil
---@type any
ImGuiStyleVar.ItemSpacing = nil
---@type any
ImGuiStyleVar.ScrollbarSize = nil
---@type any
ImGuiStyleVar.WindowBorderSize = nil
---@type any
ImGuiStyleVar.WindowPadding = nil
---@type any
ImGuiStyleVar.WindowRounding = nil

---@class NS.ImGuiWindowFlags
ImGuiWindowFlags = {}
---@type any
ImGuiWindowFlags.AlwaysAutoResize = nil
---@type any
ImGuiWindowFlags.MenuBar = nil
---@type any
ImGuiWindowFlags.NoBackground = nil
---@type any
ImGuiWindowFlags.NoBringToFrontOnFocus = nil
---@type any
ImGuiWindowFlags.NoCollapse = nil
---@type any
ImGuiWindowFlags.NoDecoration = nil
---@type any
ImGuiWindowFlags.NoMove = nil
---@type any
ImGuiWindowFlags.NoNav = nil
---@type any
ImGuiWindowFlags.NoResize = nil
---@type any
ImGuiWindowFlags.NoSavedSettings = nil
---@type any
ImGuiWindowFlags.NoScrollWithMouse = nil
---@type any
ImGuiWindowFlags.NoScrollbar = nil
---@type any
ImGuiWindowFlags.NoTitleBar = nil
---@type any
ImGuiWindowFlags.None = nil

---@type any
ImVec2 = nil

---@type any
ImVec4 = nil

---@class NS.LevelUiTextures
LevelUiTextures = {}
---@type any
LevelUiTextures.id = nil
---@type any
LevelUiTextures.path = nil

---@class NS.Texture
Texture = {}
---@type any
Texture.load = nil

---@type any
TitleFont = nil

---@type any
VulkanContext = nil

---@class NS.Wave
Wave = {}
---@type any
Wave.Register = nil
---@type any
Wave.Reset = nil
