local DamageType = (Gameplay and Gameplay.DamageType) or {
    Physical = "physical",
    Fire = "fire",
    Poison = "poison",
    Arcane = "arcane",
    Electric = "electric",
    Holy = "holy",
    Necrotic = "necrotic",
}

return {
    id = "archer_hut",
    displayName = "Archer Hut",
    model = "assets/models/towers/archer_hut/archer_hut.glb",
    projectileModel = "assets/models/towers/archer_hut/archer_hut_arrow.glb",

    stats = {
        health = 35,
        cost = 150,
        damageType = DamageType.Physical,
        armorPiercing = 1.0,
        attackDamage = 20,
        attackRange = 5.0,
        attackSpeed = 1.0,
        projectileSpeed = 16.0,
        splashRadius = 0.0,
        projectileCount = 1,
        chainTargetCount = 1,
        chainRange = 3.5,
        ricochetCount = 0,
        ricochetRange = 3.5,
    },

    render = {
        renderScale = 2.0,
        facingYawOffsetDegrees = 0.0,
    },

    upgradeTree = {
        ui = {
            panelTitle = "Archer Hut Talent Tree",
            artPath = "",
            defaultNodeIcon = "assets/images/question.png",
            accent = { 0.63, 0.45, 0.10 },
            unlocked = { 0.16, 0.55, 0.30 },
            locked = { 0.24, 0.25, 0.28 },
        },
        nodes = {
            {
                id = "stone_tip",
                displayName = "Stone Arrows",
                description = "Heavier heads for stronger impact.",
                icon = "assets/images/question.png",
                parent = "",
                childrenOrder = { "stone_shatter", "stone_penetrator" },
                branch = "stone",
                cost = 80,
                tier = 0,
                column = 0,
                excludes = { "metal_forged", "electric_capacitor" },
                effects = {
                    attackDamageAdd = 6.0,
                },
            },
            {
                id = "metal_forged",
                displayName = "Metal Fletch",
                description = "Sharper arrows and tighter spread.",
                icon = "assets/images/question.png",
                parent = "",
                childrenOrder = { "metal_overdraw", "metal_serrated" },
                branch = "metal",
                cost = 80,
                tier = 0,
                column = 1,
                maxLevel = 3,
                excludes = { "stone_tip", "electric_capacitor" },
                effects = {
                    attackSpeedAdd = 0.25,
                    attackDamageAdd = 2.0,
                },
            },
            {
                id = "electric_capacitor",
                displayName = "Spark Capacitor",
                description = "Infuses shots with unstable static charge.",
                icon = "assets/images/question.png",
                parent = "",
                childrenOrder = { "electric_chain", "electric_focus" },
                branch = "electric",
                cost = 80,
                tier = 0,
                column = 2,
                excludes = { "stone_tip", "metal_forged" },
                effects = {
                    attackRangeAdd = 0.6,
                    projectileSpeedAdd = 4.0,
                },
            },
            {
                id = "stone_shatter",
                displayName = "Shatter Volley",
                description = "Massive heads crack armor and hit harder.",
                icon = "assets/images/question.png",
                parent = "stone_tip",
                childrenOrder = { "stone_aftershock", "stone_metal_hybrid" },
                branch = "stone",
                cost = 135,
                tier = 1,
                column = 0,
                requires = { "stone_tip" },
                effects = {
                    attackDamageMul = 1.2,
                    splashRadiusAdd = 1.9,
                },
            },
            {
                id = "stone_penetrator",
                displayName = "Penetrator Heads",
                description = "Narrow stone points trade blast for piercing lanes.",
                icon = "assets/images/question.png",
                parent = "stone_tip",
                branch = "stone",
                cost = 130,
                tier = 1,
                column = 1,
                requires = { "stone_tip" },
                effects = {
                    attackDamageAdd = 4.0,
                    projectileSpeedAdd = 2.5,
                    splashRadiusAdd = -0.6,
                },
            },
            {
                id = "metal_overdraw",
                displayName = "Overdraw Rig",
                description = "Reinforced bow frame for rapid overdraw.",
                icon = "assets/images/question.png",
                parent = "metal_forged",
                childrenOrder = { "metal_triple_shot", "metal_precision" },
                branch = "metal",
                cost = 140,
                tier = 1,
                column = 1,
                requires = { "metal_forged" },
                effects = {
                    attackSpeedMul = 1.25,
                },
            },
            {
                id = "metal_serrated",
                displayName = "Serrated Vanes",
                description = "Ragged edges shred through clustered enemies.",
                icon = "assets/images/question.png",
                parent = "metal_forged",
                branch = "metal",
                cost = 145,
                tier = 1,
                column = 2,
                requires = { "metal_forged" },
                effects = {
                    attackDamageMul = 1.12,
                    ricochetCountAdd = 1,
                },
            },
            {
                id = "metal_triple_shot",
                displayName = "Triple Shot",
                description = "Fires three arrows at once and can split across targets.",
                icon = "assets/images/question.png",
                parent = "metal_overdraw",
                branch = "metal",
                cost = 190,
                tier = 2,
                column = 1,
                minUpgradesRequired = 3,
                requires = { "metal_overdraw" },
                effects = {
                    projectileCountAdd = 2,
                    attackDamageMul = 0.84,
                },
            },
            {
                id = "metal_precision",
                displayName = "Sightline Bracing",
                description = "A precision rig tightens release timing for consistent lanes.",
                icon = "assets/images/question.png",
                parent = "metal_overdraw",
                branch = "metal",
                cost = 185,
                tier = 2,
                column = 3,
                minUpgradesRequired = 3,
                requires = { "metal_overdraw" },
                effects = {
                    attackRangeAdd = 1.0,
                    attackSpeedAdd = 0.12,
                    projectileSpeedMul = 1.1,
                },
            },
            {
                id = "electric_chain",
                displayName = "Chain Arc",
                description = "Charged arrows jump between packed enemies.",
                icon = "assets/images/question.png",
                parent = "electric_capacitor",
                childrenOrder = { "electric_ricochet", "electric_static_field" },
                branch = "electric",
                cost = 145,
                tier = 1,
                column = 2,
                requires = { "electric_capacitor" },
                effects = {
                    attackRangeMul = 1.18,
                    projectileSpeedMul = 1.2,
                    chainTargetCountAdd = 2,
                    chainRangeAdd = 1.2,
                },
            },
            {
                id = "electric_focus",
                displayName = "Current Focusing",
                description = "Condenses charge into tighter arcs with longer reach.",
                icon = "assets/images/question.png",
                parent = "electric_capacitor",
                branch = "electric",
                cost = 150,
                tier = 1,
                column = 3,
                requires = { "electric_capacitor" },
                effects = {
                    attackRangeAdd = 1.1,
                    chainRangeMul = 1.15,
                },
            },
            {
                id = "electric_ricochet",
                displayName = "Arc Ricochet",
                description = "Impacts rebound to nearby enemies repeatedly.",
                icon = "assets/images/question.png",
                parent = "electric_chain",
                branch = "electric",
                cost = 180,
                tier = 2,
                column = 2,
                minUpgradesRequired = 3,
                requires = { "electric_chain" },
                effects = {
                    ricochetCountAdd = 2,
                    ricochetRangeAdd = 1.4,
                },
            },
            {
                id = "electric_static_field",
                displayName = "Static Field",
                description = "Leaves a lingering static wake that chains farther.",
                icon = "assets/images/question.png",
                parent = "electric_chain",
                branch = "electric",
                cost = 185,
                tier = 2,
                column = 5,
                minUpgradesRequired = 3,
                requires = { "electric_chain" },
                effects = {
                    chainTargetCountAdd = 1,
                    chainRangeAdd = 1.0,
                    ricochetRangeAdd = 0.8,
                },
            },
            {
                id = "stone_metal_hybrid",
                displayName = "Composite Heads",
                description = "Unlocked only by committing to either stone or metal engineering.",
                icon = "assets/images/question.png",
                parent = "stone_shatter",
                branch = "hybrid",
                cost = 170,
                tier = 2,
                column = 1,
                minUpgradesRequired = 4,
                requires = { "stone_shatter" },
                excludes = { "electric_capacitor", "electric_chain", "electric_ricochet" },
                effects = {
                    attackDamageAdd = 8.0,
                    attackSpeedAdd = 0.2,
                },
            },
            {
                id = "stone_aftershock",
                displayName = "Aftershock Bursts",
                description = "Heavy impacts kick fragments sideways into nearby lanes.",
                icon = "assets/images/question.png",
                parent = "stone_shatter",
                branch = "stone",
                cost = 175,
                tier = 2,
                column = 0,
                minUpgradesRequired = 4,
                requires = { "stone_shatter" },
                excludes = { "electric_capacitor", "electric_chain", "electric_ricochet" },
                effects = {
                    splashRadiusAdd = 1.2,
                    ricochetCountAdd = 1,
                    attackDamageMul = 1.06,
                },
            },
        },
    },
}
