local DamageType = (Gameplay and Gameplay.DamageType) or {
    Physical = "physical",
    Fire = "fire",
    Poison = "poison",
    Arcane = "arcane",
    Electric = "electric",
    Holy = "holy",
    Necrotic = "necrotic",
}

return {
    id = "archer_hut",
    displayName = "Archer Hut",
    bio = "A frontier watchpost crewed by disciplined bowyers. Archer Huts favor lane control, and can be tuned from heavy impact volleys to chain-hopping electric harassment.",
    model = "assets/models/towers/archer_hut/archer_hut.glb",
    projectileModel = "assets/models/towers/archer_hut/archer_hut_arrow.glb",

    stats = {
        health = 35,
        cost = 150,
        damageType = DamageType.Physical,
        targetMode = "first",
        armorPiercing = 1.0,
        attackDamage = 20,
        attackRange = 5.0,
        attackSpeed = 1.0,
        projectileSpeed = 16.0,
        splashRadius = 0.0,
        projectileCount = 1,
        chainTargetCount = 1,
        chainRange = 3.5,
        ricochetCount = 0,
        ricochetRange = 3.5,
    },

    render = {
        renderScale = 2.0,
        facingYawOffsetDegrees = 0.0,
    },

    upgradeTree = {
        ui = {
            panelTitle = "Archer Hut Talent Tree",
            artPath = "",
            defaultNodeIcon = "assets/images/talents/archer/archer_quickdraw_rig.png",
            accent = { 0.63, 0.45, 0.10 },
            unlocked = { 0.16, 0.55, 0.30 },
            locked = { 0.24, 0.25, 0.28 },
        },
        nodes = {
            {
                id = "quickdraw_rig",
                displayName = "Quickdraw Rig",
                description = "A tuned bow rig that increases firing cadence.",
                icon = "assets/images/talents/archer/archer_quickdraw_rig.png",
                parent = "",
                childrenOrder = { "hardened_draw" },
                branch = "core",
                tier = 0,
                column = 1,
                upgradeLevels = {
                    {
                        cost = 90,
                        effects = {
                            attackSpeedAdd = 0.5,
                        },
                    },
                    {
                        cost = 150,
                        effects = {
                            attackSpeedAdd = 1.5,
                        },
                    },
                },
            },
            {
                id = "hardened_draw",
                displayName = "Hardened Draw",
                description = "Reinforced limbs transfer more force into every shot.",
                icon = "assets/images/talents/archer/archer_hardened_draw.png",
                parent = "quickdraw_rig",
                childrenOrder = { "stone_specialization", "metal_specialization", "electric_specialization" },
                branch = "core",
                tier = 1,
                column = 1,
                requires = { "quickdraw_rig" },
                upgradeLevels = {
                    {
                        cost = 130,
                        effects = {
                            attackDamageAdd = 7.0,
                        },
                    },
                },
            },
            {
                id = "stone_specialization",
                displayName = "Stone Specialization",
                description = "Heavy stone heads trade finesse for crushing impact.",
                icon = "assets/images/talents/archer/archer_stone_specialization.png",
                parent = "hardened_draw",
                childrenOrder = { "stone_shatter", "stone_penetrator" },
                branch = "stone",
                tier = 2,
                column = 0,
                minUpgradesRequired = 2,
                requires = { "hardened_draw" },
                excludes = { "metal_specialization", "electric_specialization" },
                upgradeLevels = {
                    {
                        cost = 180,
                        effects = {
                            attackDamageMul = 1.20,
                            splashRadiusAdd = 1.1,
                            projectileSpeedMul = 0.92,
                        },
                    },
                },
            },
            {
                id = "metal_specialization",
                displayName = "Metal Specialization",
                description = "Forged heads favor fast puncture and repeated hits.",
                icon = "assets/images/talents/archer/archer_metal_specialization.png",
                parent = "hardened_draw",
                childrenOrder = { "metal_overdraw", "metal_serrated" },
                branch = "metal",
                tier = 2,
                column = 1,
                minUpgradesRequired = 2,
                requires = { "hardened_draw" },
                excludes = { "stone_specialization", "electric_specialization" },
                upgradeLevels = {
                    {
                        cost = 180,
                        effects = {
                            attackSpeedMul = 1.14,
                            projectileCountAdd = 1,
                            attackDamageMul = 0.88,
                        },
                    },
                },
            },
            {
                id = "electric_specialization",
                displayName = "Electric Specialization",
                description = "Charged arrows arc between targets in packed lanes.",
                icon = "assets/images/talents/archer/archer_electric_specialization.png",
                parent = "hardened_draw",
                childrenOrder = { "electric_chain", "electric_focus" },
                branch = "electric",
                tier = 2,
                column = 2,
                minUpgradesRequired = 2,
                requires = { "hardened_draw" },
                excludes = { "stone_specialization", "metal_specialization" },
                upgradeLevels = {
                    {
                        cost = 180,
                        effects = {
                            projectileSpeedMul = 1.2,
                            attackRangeAdd = 0.8,
                            chainTargetCountAdd = 1,
                            chainRangeAdd = 1.2,
                        },
                    },
                },
            },
            {
                id = "stone_shatter",
                displayName = "Shatter Volley",
                description = "Massive heads crack armor and hit harder.",
                icon = "assets/images/talents/archer/archer_stone_shatter.png",
                parent = "stone_specialization",
                childrenOrder = { "stone_aftershock", "stone_metal_hybrid" },
                branch = "stone",
                tier = 3,
                column = 0,
                minUpgradesRequired = 3,
                requires = { "stone_specialization" },
                upgradeLevels = {
                    {
                        cost = 135,
                        effects = {
                            attackDamageMul = 1.20,
                            splashRadiusAdd = 1.9,
                        },
                    },
                },
            },
            {
                id = "stone_penetrator",
                displayName = "Penetrator Heads",
                description = "Narrow stone points trade blast for piercing lanes.",
                icon = "assets/images/talents/archer/archer_stone_penetrator.png",
                parent = "stone_specialization",
                branch = "stone",
                tier = 3,
                column = 1,
                minUpgradesRequired = 3,
                requires = { "stone_specialization" },
                upgradeLevels = {
                    {
                        cost = 130,
                        effects = {
                            attackDamageAdd = 4.0,
                            projectileSpeedAdd = 2.5,
                            splashRadiusAdd = -0.6,
                        },
                    },
                },
            },
            {
                id = "metal_overdraw",
                displayName = "Overdraw Rig",
                description = "Reinforced bow frame for rapid overdraw.",
                icon = "assets/images/talents/archer/archer_metal_overdraw.png",
                parent = "metal_specialization",
                childrenOrder = { "metal_triple_shot", "metal_precision" },
                branch = "metal",
                tier = 3,
                column = 1,
                minUpgradesRequired = 3,
                requires = { "metal_specialization" },
                upgradeLevels = {
                    {
                        cost = 140,
                        effects = {
                            attackSpeedMul = 1.25,
                        },
                    },
                },
            },
            {
                id = "metal_serrated",
                displayName = "Serrated Vanes",
                description = "Ragged edges shred through clustered enemies.",
                icon = "assets/images/talents/archer/archer_metal_serrated.png",
                parent = "metal_specialization",
                branch = "metal",
                tier = 3,
                column = 2,
                minUpgradesRequired = 3,
                requires = { "metal_specialization" },
                upgradeLevels = {
                    {
                        cost = 145,
                        effects = {
                            attackDamageMul = 1.12,
                            ricochetCountAdd = 1,
                        },
                    },
                },
            },
            {
                id = "electric_chain",
                displayName = "Chain Arc",
                description = "Charged arrows jump between packed enemies.",
                icon = "assets/images/talents/archer/archer_electric_chain.png",
                parent = "electric_specialization",
                childrenOrder = { "electric_ricochet", "electric_static_field" },
                branch = "electric",
                tier = 3,
                column = 2,
                minUpgradesRequired = 3,
                requires = { "electric_specialization" },
                upgradeLevels = {
                    {
                        cost = 145,
                        effects = {
                            attackRangeMul = 1.18,
                            projectileSpeedMul = 1.2,
                            chainTargetCountAdd = 2,
                            chainRangeAdd = 1.2,
                        },
                    },
                },
            },
            {
                id = "electric_focus",
                displayName = "Current Focusing",
                description = "Condenses charge into tighter arcs with longer reach.",
                icon = "assets/images/talents/archer/archer_electric_focus.png",
                parent = "electric_specialization",
                branch = "electric",
                tier = 3,
                column = 3,
                minUpgradesRequired = 3,
                requires = { "electric_specialization" },
                upgradeLevels = {
                    {
                        cost = 150,
                        effects = {
                            attackRangeAdd = 1.1,
                            chainRangeMul = 1.15,
                        },
                    },
                },
            },
            {
                id = "metal_triple_shot",
                displayName = "Triple Shot",
                description = "Fires three arrows at once and can split across targets.",
                icon = "assets/images/talents/archer/archer_metal_triple_shot.png",
                parent = "metal_overdraw",
                branch = "metal",
                tier = 4,
                column = 1,
                minUpgradesRequired = 4,
                requires = { "metal_overdraw" },
                upgradeLevels = {
                    {
                        cost = 190,
                        effects = {
                            projectileCountAdd = 2,
                            attackDamageMul = 0.84,
                        },
                    },
                },
            },
            {
                id = "metal_precision",
                displayName = "Sightline Bracing",
                description = "A precision rig tightens release timing for consistent lanes.",
                icon = "assets/images/talents/archer/archer_metal_precision.png",
                parent = "metal_overdraw",
                branch = "metal",
                tier = 4,
                column = 3,
                minUpgradesRequired = 4,
                requires = { "metal_overdraw" },
                upgradeLevels = {
                    {
                        cost = 185,
                        effects = {
                            attackRangeAdd = 1.0,
                            attackSpeedAdd = 0.12,
                            projectileSpeedMul = 1.1,
                        },
                    },
                },
            },
            {
                id = "electric_ricochet",
                displayName = "Arc Ricochet",
                description = "Impacts rebound to nearby enemies repeatedly.",
                icon = "assets/images/talents/archer/archer_electric_ricochet.png",
                parent = "electric_chain",
                branch = "electric",
                tier = 4,
                column = 2,
                minUpgradesRequired = 4,
                requires = { "electric_chain" },
                upgradeLevels = {
                    {
                        cost = 180,
                        effects = {
                            ricochetCountAdd = 2,
                            ricochetRangeAdd = 1.4,
                        },
                    },
                },
            },
            {
                id = "electric_static_field",
                displayName = "Static Field",
                description = "Leaves a lingering static wake that chains farther.",
                icon = "assets/images/talents/archer/archer_electric_static_field.png",
                parent = "electric_chain",
                branch = "electric",
                tier = 4,
                column = 5,
                minUpgradesRequired = 4,
                requires = { "electric_chain" },
                upgradeLevels = {
                    {
                        cost = 185,
                        effects = {
                            chainTargetCountAdd = 1,
                            chainRangeAdd = 1.0,
                            ricochetRangeAdd = 0.8,
                        },
                    },
                },
            },
            {
                id = "stone_metal_hybrid",
                displayName = "Composite Heads",
                description = "Unlocked only by committing to either stone or metal engineering.",
                icon = "assets/images/talents/archer/archer_stone_metal_hybrid.png",
                parent = "stone_shatter",
                branch = "hybrid",
                tier = 4,
                column = 1,
                minUpgradesRequired = 5,
                requires = { "stone_shatter" },
                excludes = { "electric_specialization", "electric_chain", "electric_ricochet" },
                upgradeLevels = {
                    {
                        cost = 170,
                        effects = {
                            attackDamageAdd = 8.0,
                            attackSpeedAdd = 0.2,
                        },
                    },
                },
            },
            {
                id = "stone_aftershock",
                displayName = "Aftershock Bursts",
                description = "Heavy impacts kick fragments sideways into nearby lanes.",
                icon = "assets/images/talents/archer/archer_stone_aftershock.png",
                parent = "stone_shatter",
                branch = "stone",
                tier = 4,
                column = 0,
                minUpgradesRequired = 5,
                requires = { "stone_shatter" },
                excludes = { "electric_specialization", "electric_chain", "electric_ricochet" },
                upgradeLevels = {
                    {
                        cost = 175,
                        effects = {
                            splashRadiusAdd = 1.2,
                            ricochetCountAdd = 1,
                            attackDamageMul = 1.06,
                        },
                    },
                },
            },
        },
    },
}
